name: nowplaying
description: A plugin to reveal metadata for the currently playing audio track
repository: https://github.com/shinyford/nowplaying
version: 2.1.0

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  package_info: ^2.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  platform: ^3.1.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  plugin:
    platforms:
      android:
        package: com.gomes.nowplaying
        pluginClass: NowPlayingPlugin
      ios:
        pluginClass: NowPlayingPlugin

  assets:
    - assets/apple_music.png
